CREATE TABLE IF NOT EXISTS account (
  id        INTEGER         NOT NULL AUTO_INCREMENT,
  username VARCHAR(128)    NOT NULL,
  password   VARCHAR(512)    NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS memo (
  id INTEGER NOT NULL AUTO_INCREMENT,
  text VARCHAR(512) NOT NULL,
  account_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (account_id) REFERENCES account(id)
);